parameters:
#    vectorface_backlog.example.class: Vectorface\BacklogBundle\Example

services:
    RedisService:
        class: Vectorface\BacklogBundle\Service\RedisService
        calls:
            - [setContainer, [@service_container]]
    FogbugzService:
        class: Vectorface\BacklogBundle\Service\FogbugzService
        arguments: ["@RedisService"]
        calls:
            - [setContainer, [@service_container]]