parameters:
#    vectorface_backlog.example.class: Vectorface\BacklogBundle\Example

services:
    redisservice:
        class: Vectorface\BacklogBundle\Service\RedisService
        calls:
            - [setConfig, ["%redis%"]]
    fogbugzservice:
        class: Vectorface\BacklogBundle\Service\FogbugzService
        arguments: ["@RedisService"]
        calls:
            - [setConfig, ["%fogbugz%"]]
    Vectorface.twig.fogbugz_extension:
        class: Vectorface\BacklogBundle\Twig\Extension\FogbugzExtension
        tags:
            - { name: twig.extension }
        arguments: ["%fogbugz%"]